### ISSUE TITLE
[Android App] Update default colors & add configuration

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1849]
- [ ] Replace the primary (pink) color: #3062d6
- [ ] Make the gray block surrounding text transparent
- [ ] Replace the default bot message color: #f2f2f2
- [ ] Replace the default user message bg color: #3062d6
- [ ] Replace the default user text color: #ffffff
- [ ] Add configuration for bot and user message colors - preconfigured list or any hex?
- [ ] Add configuration for user text colors - #000000 or #ffffff only

**Comment by abiemann** [comment]
for the default bot text color, I used #000000
