### ISSUE TITLE
Release Testing Checklist

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#1962]
@darrenj, @lzc850612, @ryanlengel - Please add any additional checklist items as you see fit. 

**Bugs found:**
- ~Skill.Tests project referencing Bot.Builder 4.5.0~
- ~Fix luis and qna id capitalization in mainDialog and botTestBase~
- ~update_cognitive_models.ps1 missing luisgen call~
- ~update_cognitive_models.ps1 from the skill complains about 'qna_functions.ps1' do not exist and tries to update dispatch model when it doesn't exist on the skill~

**Comment by lauren-mills** [comment]
@lauren-mills:

**VA**
- [x] install bot tools (use ludown 1.3.1)
- [x] Create a VA
- [x] Verify it builds and tests pass
- [x] Deploy in non-luisAuthoring region (i.e. centralus)
- [x] Verify everything deploys correctly (**needs id capitalization fix**)
- [x] In luis.ai, make a change to your general model (train, and publish)
- [x] Then run update_cognitive_models -remoteToLocal
- [x] Verify your local general.lu and dispatch models have changed, LuisGen has regenerated, and you can test your new utterance
- [x] Remove the intent you added directly in the lu file, then run update_cognitive_models
- [x] Verify dispatch, hosted luis model, and lg file have correctly updated (**needs luisgen fix**)
- [x] Teams channel
- [x] Webchat channel

 
**Skill**
- [x] Verify it builds and tests pass (**needs bot.builder 4.5.1 fix**)
- [x] deploy
- [x] Verify you can access the manifest endpoint
- [x] Add your skill to your VA using botskills connect
- [x] Verify you can call your skill from VA
- [x] update your skill luis model
- [x] run update cognitive models -remotetolocal
- [x] verify the lu file and lg files update correctly
- [x] update your manifest
- [x] publish using the publish.ps1 script
- [x] run botskills refresh on your VA 
- [x] verify the dispatch model and skills.json is updated

**Skills**
- [x] Calendar (Deploy, Add to VA)
- [ ] Email (Deploy, Add to VA) (**Failed due to ludown issue #1963, microsoft/botbuilder-tools/issues/1225**)
**Skills**
- [x] Automotive Skill (deploy, add to VA)

**Comment by lauren-mills** [comment]
@ryanlengel:

**VA**
- [ ] install bot tools (use ludown 1.3.1)
- [ ] Create a VA
- [ ] Verify it builds and tests pass
- [ ] Deploy in non-luisAuthoring region (i.e. centralus)
- [ ] Verify everything deploys correctly
- [ ] In luis.ai, make a change to your general model (train, and publish)
- [ ] Then run update_cognitive_models -remoteToLocal
- [ ] Verify your local general.lu and dispatch models have changed, LuisGen has regenerated, and you can test your new utterance
- [ ] Remove the intent you added directly in the lu file, then run update_cognitive_models
- [ ] Verify dispatch, hosted luis model, and lg file have correctly updated
- [ ] Speech channel
 
Skill

- [ ] Verify it builds and tests pass
- [ ] deploy
- [ ] Verify you can access the manifest endpoint
- [ ] Add your skill to your VA using botskills connect
- [ ] update your skill luis model
- [ ] run update cognitive models -remotetolocal
- [ ] verify the lu file and lg files update correctly
- [ ] update your manifest
- [ ] publish using the publish.ps1 script
- [ ] run botskills refresh on your VA 
- [ ] verify the dispatch model and skills.json is updated

**Comment by lauren-mills** [comment]
@lzc850612 :
**VA**
- [x] install bot tools (use ludown 1.3.1)
- [x] Create a VA
- [x] Verify it builds and tests pass
- [x] Deploy in non-luisAuthoring region (i.e. centralus)
- [x] Verify everything deploys correctly
- [x] In luis.ai, make a change to your general model (train, and publish)
- [x] Then run update_cognitive_models -remoteToLocal
- [x] Verify your local general.lu and dispatch models have changed, LuisGen has regenerated, and you can test your new utterance
- [x] Remove the intent you added directly in the lu file, then run update_cognitive_models
- [x] Verify dispatch, hosted luis model, and lg file have correctly updated
- [x] Speechchannel
 
**Skill**
- [x] Verify it builds and tests pass
- [x] deploy
- [x] Verify you can access the manifest endpoint
- [x] Add your skill to your VA using botskills connect
- [x] update your skill luis model
- [x] run update cognitive models -remotetolocal
- [x] verify the lu file and lg files update correctly
- [x] update your manifest
- [x] publish using the publish.ps1 script
- [x] run botskills refresh on your VA 
- [x] verify the dispatch model and skills.json is updated

**Skills**
- [x] POI skill (deploy, add to VA)
- [x] ToDo (deploy, add to VA)  (**Failed due to ludown issue #1963, microsoft/botbuilder-tools/issues/1225**)
