### ISSUE TITLE
0.7 Release Checklist

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2415]
**Before merging into master**
- [ ] Validate all aka.ms links
- [ ] Validate VA preview environment builds
- [ ] Validate skill preview environment builds
- [ ] Update to 4.6 SDK libs
- [ ] Update documentation with any manual changes needed for existing VAs and Skills
