### ISSUE TITLE
[POI] Add Foursquare provider support so POI details can be displayed to the user

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#571]
**Is your feature request related to a problem? Please describe.**
When returning POI results, provide the following details about a POI (if available): 
* Provider (content provider)
* Thumbnail URL (image of the POI)
* Bookable
* Rating
* Price level
* Phone Number
* Categories
* Business hours

**Describe the solution you'd like**
Investigate using Foursquare's API as a component or alternative to Azure Maps in order to return these business details. 

As a component, this may result is multiple API calls for a single bot response and should be used for POC demonstrations only.  Example, using a POI intent with KEYWORD matched:
1. **Get Search POI** with query=KEYWORD to get POI name, location, category, etc.
2. For each POI (3 by default), call **POI Details API** to get rating, price level, etc.
3. **Get Route Directions** to navigate to selected POI.

If used as an alternative, the API may not be flexible enough to easily transpose API usage but this will require further investigation.

**Describe alternatives you've considered**

**Additional context**
**Tasks**
- [x] Generalize PointOfInterestModel to work with both Azure Maps & Foursquare
- [x] Add Foursquare Configuration
- [x] Implement Foursquare Nearby Venues API
- [x] Implement Foursquare Search Venues API
- [x] Implement Foursquare Venue Details API
- [x] Testing
