### ISSUE TITLE
[POI] Provide sample event architecture & state for common location

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#595]
**Is your feature request related to a problem? Please describe.**

The POI skill should show samples for common locations a user may have that can be set from an embedded system.

**Describe the solution you'd like**

Add new Home/Office POIs in state data and rename ActiveLocation to Destination.
These can be set with new events `IPA.Destination`, `IPA.Home`, `IPA.Office` and lat/lon coordinate values.
Add `COMMON_LOCATION` phrase list LUIS entity to capture: here, destination, home, office. These can be used in a dialog's logic to determine the required "current coordinates."

**Tasks**
- [x] Add COMMON_LOCATION phrase list entity to language model
- [x] Add the Destination, Home, and Office PointOfInterestModels to PointOfInterestState
- [x] Add event support for `IPA.Destination`, `IPA.Home`, `IPA.Office`
- [x] Update dialog and methods for sending current coordinates to GeospatialService
- [x] Testing

**Comment by ryanisgrig** [comment]
Closing as this is POC work.
